# Passing

In [1]:
import pandas as pd

In [2]:
df = pd.read_pickle('passing')

In [3]:
df.head()

,PLAYER,POSITION,TEAM,GP,ATT,CMP,PCT,YDS,YDSpG,LNG,TD,INT,SCK,YDSL,RATE
0,Matt Ryan,QB,ATL,1,54,37,68.5,450,450.0,44,2,1,2,16,98.5
1,Aaron Rodgers,QB,GB,1,44,32,72.7,364,364.0,45,4,0,0,0,127.5
2,Philip Rivers,QB,IND,1,46,36,78.3,363,363.0,35,1,2,0,0,88.7
3,Russell Wilson,QB,SEA,1,35,31,88.6,322,322.0,38,4,0,3,23,143.1
4,Josh Allen,QB,BUF,1,46,33,71.7,312,312.0,29,2,0,3,6,104.6

In [4]:
df[df['PLAYER'].isin(['Aaron Rodgers', 'Dak Prescott', 'Carson Wentz'])]

,PLAYER,POSITION,TEAM,GP,ATT,CMP,PCT,YDS,YDSpG,LNG,TD,INT,SCK,YDSL,RATE
1,Aaron Rodgers,QB,GB,1,44,32,72.7,364,364.0,45,4,0,0,0,127.5
9,Carson Wentz,QB,PHI,1,42,24,57.1,270,270.0,55,2,2,8,62,72.5
11,Dak Prescott,QB,DAL,1,39,25,64.1,266,266.0,33,1,0,3,22,92.5

In [5]:
columns = ['GP', 'ATT', 'CMP', 'YDS', 'LNG', 'TD', 'INT', 'SCK', 'YDSL']
percents = ['PCT', 'YDSpG', 'RATE']

In [7]:
dash = df['PCT'][34]
val = dash

In [8]:
for column in columns:
    for i in range(len(df[column])):
        item = df[column][i]
        if item == val:
            df[column][i] = '0'
        else:
            df[column][i] = item

In [9]:
for column in columns:
    df[column] = df[column].map(lambda x: int(x))

In [10]:
for column in percents:
    for i in range(len(df[column])):
        item = df[column][i]
        if item == val:
            df[column][i] = '0.0'
        else:
            df[column][i] = item

/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  import sys
/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """

In [11]:
for column in percents:
    for i in range(len(df[column])):
        item = str(df[column][i])
        ones, tenths = item.split('.')
        ones = int(ones)
        tenths = int(tenths) * .1
        df[column][i] = ones + tenths

/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  import sys

In [13]:
df.dtypes

PLAYER      object
POSITION    object
TEAM        object
GP           int64
ATT          int64
CMP          int64
PCT         object
YDS          int64
YDSpG       object
LNG          int64
TD           int64
INT          int64
SCK          int64
YDSL         int64
RATE        object
dtype: object

In [14]:
df.sort_values('RATE', ascending = False)

,PLAYER,POSITION,TEAM,GP,ATT,CMP,PCT,YDS,YDSpG,LNG,TD,INT,SCK,YDSL,RATE
8,Lamar Jackson,QB,BAL,1,25,20,80,275,275,47,3,0,2,14,152.1
3,Russell Wilson,QB,SEA,1,35,31,88.6,322,322,38,4,0,3,23,143.1
29,Gardner Minshew,QB,JAC,1,20,19,95,173,173,28,3,0,4,23,142.3
1,Aaron Rodgers,QB,GB,1,44,32,72.7,364,364,45,4,0,0,0,127.5
23,Patrick Mahomes,QB,KC,1,32,24,75,211,211,19,3,0,1,8,123.3
32,Taysom Hill,QB,NO,1,1,1,100,38,38,38,0,0,0,0,118.8
12,Kirk Cousins,QB,MIN,1,25,19,76,259,259,37,2,1,2,11,118.6
20,Ben Roethlisberger,QB,PIT,1,32,21,65.6,229,229,28,3,0,2,21,117.8
18,Derek Carr,QB,LV,1,30,22,73.3,239,239,45,1,0,0,0,107.5
4,Josh Allen,QB,BUF,1,46,33,71.7,312,312,29,2,0,3,6,104.6
16,Mitchell Trubisky,QB,CHI,1,36,20,55.6,242,242,27,3,0,1,28,104.2
33,Robert Griffin III,QB,BAL,1,1,1,100,9,9,9,0,0,0,0,104.2
13,Jimmy Garoppolo,QB,SF,1,33,19,57.6,259,259,76,2,0,3,16,103
31,Cam Newton,QB,NE,1,19,15,78.9,155,155,25,0,0,2,15,100.7
10,Teddy Bridgewater,QB,CAR,1,34,22,64.7,269,269,75,1,0,1,10,98.8
0,Matt Ryan,QB,ATL,1,54,37,68.5,450,450,44,2,1,2,16,98.5
15,Ryan Tannehill,QB,TEN,1,43,29,67.4,249,249,23,2,0,1,2,97.9
30,Drew Brees,QB,NO,1,30,18,60,160,160,46,2,0,1,9,96.5
21,Drew Lock,QB,DEN,1,33,22,66.7,216,216,31,1,0,0,0,95
11,Dak Prescott,QB,DAL,1,39,25,64.1,266,266,33,1,0,3,22,92.5
2,Philip Rivers,QB,IND,1,46,36,78.3,363,363,35,1,2,0,0,88.7
14,Deshaun Watson,QB,HOU,1,32,20,62.5,253,253,31,1,1,4,11,84.5
28,Dwayne Haskins,QB,WAS,1,31,17,54.8,178,178,21,1,0,3,19,82.5
7,Jared Goff,QB,LAR,1,31,20,64.5,275,275,31,0,1,1,6,79.4
6,Daniel Jones,QB,NYG,1,41,26,63.4,279,279,41,2,2,3,17,79.2
17,Tom Brady,QB,TB,1,36,23,63.9,239,239,37,2,2,3,15,78.4
19,Kyler Murray,QB,ARI,1,40,26,65,230,230,33,1,1,2,6,78.1
5,Matthew Stafford,QB,DET,1,42,24,57.1,297,297,32,1,1,1,9,77.2
24,Tyrod Taylor,QB,LAC,1,30,16,53.3,208,208,37,0,0,2,1,75.4
22,Sam Darnold,QB,NYJ,1,35,21,60,215,215,69,1,1,3,13,75.3
9,Carson Wentz,QB,PHI,1,42,24,57.1,270,270,55,2,2,8,62,72.5
25,Joe Burrow,QB,CIN,1,36,23,63.9,193,193,19,0,1,3,20,66.1
27,Baker Mayfield,QB,CLE,1,39,21,53.8,189,189,28,1,1,2,21,65
26,Ryan Fitzpatrick,QB,MIA,1,30,20,66.7,191,191,21,0,3,1,9,44.6
34,Jacoby Brissett,QB,IND,1,0,0,0,0,0,0,0,0,1,6,0